title: <p align="center">Auliya Nur Asyifa</p>
logo: "/images/photo-profile.png?raw=true"
description: # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  # <a href="pdf/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/auliyanra/">LinkedIn</a> |
  <a href="https://github.com/auliyanurasyifa">GitHub</a>
  </p>
  
  <p align="justify">
  I am currently a final-year student at Gadjah Mada University pursuing an undergraduate degree, majoring in Mathematics. 
  <br><br>
  I am interested in data analytics and financial mathematics.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
